import chainMail from './armor/chainMail.js'
chainMail.name = 'chainMail'
import leatherArmor from './armor/leatherArmor.js'
leatherArmor.name = 'leatherArmor'
import platemail from './armor/platemail.js'
platemail.name = 'platemail'
import rags from './armor/rags.js'
rags.name = 'rags'
import scholarsRobe from './armor/scholarsRobe.js'
scholarsRobe.name = 'scholarsRobe'
import fencingBoots from './boots/fencingBoots.js'
fencingBoots.name = 'fencingBoots'
import hikingBoots from './boots/hikingBoots.js'
hikingBoots.name = 'hikingBoots'
import expeditionMap from './misc/expeditionMap.js'
expeditionMap.name = 'expeditionMap'
import luckyRing from './rings/luckyRing.js'
luckyRing.name = 'luckyRing'
import staminaRing from './rings/staminaRing.js'
staminaRing.name = 'staminaRing'
import vampiricRing from './rings/vampiricRing.js'
vampiricRing.name = 'vampiricRing'
import cursedSword from './weapons/cursedSword.js'
cursedSword.name = 'cursedSword'
import dagger from './weapons/dagger.js'
dagger.name = 'dagger'
import heavyAxe from './weapons/heavyAxe.js'
heavyAxe.name = 'heavyAxe'
import sword from './weapons/sword.js'
sword.name = 'sword'
import warHammer from './weapons/warHammer.js'
warHammer.name = 'warHammer'
import whip from './weapons/whip.js'
whip.name = 'whip'
export default { CHAINMAIL:chainMail,LEATHERARMOR:leatherArmor,PLATEMAIL:platemail,RAGS:rags,SCHOLARSROBE:scholarsRobe,FENCINGBOOTS:fencingBoots,HIKINGBOOTS:hikingBoots,EXPEDITIONMAP:expeditionMap,LUCKYRING:luckyRing,STAMINARING:staminaRing,VAMPIRICRING:vampiricRing,CURSEDSWORD:cursedSword,DAGGER:dagger,HEAVYAXE:heavyAxe,SWORD:sword,WARHAMMER:warHammer,WHIP:whip }