import fencingBoots from './boots/fencingBoots.js'
fencingBoots.name = 'fencingBoots'
import hikingBoots from './boots/hikingBoots.js'
hikingBoots.name = 'hikingBoots'
import steelBoots from './boots/steelBoots.js'
steelBoots.name = 'steelBoots'
import chainMail from './armor/chainMail.js'
chainMail.name = 'chainMail'
import leatherArmor from './armor/leatherArmor.js'
leatherArmor.name = 'leatherArmor'
import legendaryArmor from './armor/legendaryArmor.js'
legendaryArmor.name = 'legendaryArmor'
import platemail from './armor/platemail.js'
platemail.name = 'platemail'
import rags from './armor/rags.js'
rags.name = 'rags'
import scholarsRobe from './armor/scholarsRobe.js'
scholarsRobe.name = 'scholarsRobe'
import expeditionMap from './misc/expeditionMap.js'
expeditionMap.name = 'expeditionMap'
import frenzyRing from './rings/frenzyRing.js'
frenzyRing.name = 'frenzyRing'
import luckyRing from './rings/luckyRing.js'
luckyRing.name = 'luckyRing'
import staminaRing from './rings/staminaRing.js'
staminaRing.name = 'staminaRing'
import vampiricRing from './rings/vampiricRing.js'
vampiricRing.name = 'vampiricRing'
import bigDumbHammer from './weapons/bigDumbHammer.js'
bigDumbHammer.name = 'bigDumbHammer'
import cursedSword from './weapons/cursedSword.js'
cursedSword.name = 'cursedSword'
import dagger from './weapons/dagger.js'
dagger.name = 'dagger'
import heavyAxe from './weapons/heavyAxe.js'
heavyAxe.name = 'heavyAxe'
import machete from './weapons/machete.js'
machete.name = 'machete'
import sword from './weapons/sword.js'
sword.name = 'sword'
import warHammer from './weapons/warHammer.js'
warHammer.name = 'warHammer'
import whip from './weapons/whip.js'
whip.name = 'whip'
export default { FENCINGBOOTS:fencingBoots,HIKINGBOOTS:hikingBoots,STEELBOOTS:steelBoots,CHAINMAIL:chainMail,LEATHERARMOR:leatherArmor,LEGENDARYARMOR:legendaryArmor,PLATEMAIL:platemail,RAGS:rags,SCHOLARSROBE:scholarsRobe,EXPEDITIONMAP:expeditionMap,FRENZYRING:frenzyRing,LUCKYRING:luckyRing,STAMINARING:staminaRing,VAMPIRICRING:vampiricRing,BIGDUMBHAMMER:bigDumbHammer,CURSEDSWORD:cursedSword,DAGGER:dagger,HEAVYAXE:heavyAxe,MACHETE:machete,SWORD:sword,WARHAMMER:warHammer,WHIP:whip }