import bat from './section1/bat.js'
bat.name = 'bat'
import kobold from './section1/kobold.js'
kobold.name = 'kobold'
import minotaur from './section1/minotaur.js'
minotaur.name = 'minotaur'
import ooze from './section1/ooze.js'
ooze.name = 'ooze'
import rat from './section1/rat.js'
rat.name = 'rat'
import rockGolem from './section1/rockGolem.js'
rockGolem.name = 'rockGolem'
import scorpion from './section1/scorpion.js'
scorpion.name = 'scorpion'
import sorcerer from './section1/sorcerer.js'
sorcerer.name = 'sorcerer'
import spider from './section1/spider.js'
spider.name = 'spider'
import troglodyte from './section1/troglodyte.js'
troglodyte.name = 'troglodyte'
import abomination from './section2/abomination.js'
abomination.name = 'abomination'
import banshee from './section2/banshee.js'
banshee.name = 'banshee'
import boneDragon from './section2/boneDragon.js'
boneDragon.name = 'boneDragon'
import lich from './section2/lich.js'
lich.name = 'lich'
import necromancer from './section2/necromancer.js'
necromancer.name = 'necromancer'
import shade from './section2/shade.js'
shade.name = 'shade'
import skeleton from './section2/skeleton.js'
skeleton.name = 'skeleton'
import vampire from './section2/vampire.js'
vampire.name = 'vampire'
import wraith from './section2/wraith.js'
wraith.name = 'wraith'
import zombie from './section2/zombie.js'
zombie.name = 'zombie'
export default { BAT:bat,KOBOLD:kobold,MINOTAUR:minotaur,OOZE:ooze,RAT:rat,ROCKGOLEM:rockGolem,SCORPION:scorpion,SORCERER:sorcerer,SPIDER:spider,TROGLODYTE:troglodyte,ABOMINATION:abomination,BANSHEE:banshee,BONEDRAGON:boneDragon,LICH:lich,NECROMANCER:necromancer,SHADE:shade,SKELETON:skeleton,VAMPIRE:vampire,WRAITH:wraith,ZOMBIE:zombie }