import bat from './section1/bat.js'
bat.name = 'bat'
import kobold from './section1/kobold.js'
kobold.name = 'kobold'
import minotaur from './section1/minotaur.js'
minotaur.name = 'minotaur'
import ooze from './section1/ooze.js'
ooze.name = 'ooze'
import rat from './section1/rat.js'
rat.name = 'rat'
import rockGolem from './section1/rockGolem.js'
rockGolem.name = 'rockGolem'
import scorpion from './section1/scorpion.js'
scorpion.name = 'scorpion'
import sorcerer from './section1/sorcerer.js'
sorcerer.name = 'sorcerer'
import spider from './section1/spider.js'
spider.name = 'spider'
import troglodyte from './section1/troglodyte.js'
troglodyte.name = 'troglodyte'
export default { BAT:bat,KOBOLD:kobold,MINOTAUR:minotaur,OOZE:ooze,RAT:rat,ROCKGOLEM:rockGolem,SCORPION:scorpion,SORCERER:sorcerer,SPIDER:spider,TROGLODYTE:troglodyte }