import addStatusEffect from './common/addStatusEffect.js'
addStatusEffect.name = 'addStatusEffect'
addStatusEffect.group = 'common'
import attack from './common/attack.js'
attack.name = 'attack'
attack.group = 'common'
import dealDamage from './common/dealDamage.js'
dealDamage.name = 'dealDamage'
dealDamage.group = 'common'
import editCooldowns from './common/editCooldowns.js'
editCooldowns.name = 'editCooldowns'
editCooldowns.group = 'common'
import editStatusEffect from './common/editStatusEffect.js'
editStatusEffect.name = 'editStatusEffect'
editStatusEffect.group = 'common'
import editTurnTime from './common/editTurnTime.js'
editTurnTime.name = 'editTurnTime'
editTurnTime.group = 'common'
import gainHealth from './common/gainHealth.js'
gainHealth.name = 'gainHealth'
gainHealth.group = 'common'
import idle from './common/idle.js'
idle.name = 'idle'
idle.group = 'common'
import removeStatusEffect from './common/removeStatusEffect.js'
removeStatusEffect.name = 'removeStatusEffect'
removeStatusEffect.group = 'common'
import takeDamage from './common/takeDamage.js'
takeDamage.name = 'takeDamage'
takeDamage.group = 'common'
export default {
  common: { addStatusEffect,attack,dealDamage,editCooldowns,editStatusEffect,editTurnTime,gainHealth,idle,removeStatusEffect,takeDamage },
}
export const all = { addStatusEffect,attack,dealDamage,editCooldowns,editStatusEffect,editTurnTime,gainHealth,idle,removeStatusEffect,takeDamage }
export { addStatusEffect as addStatusEffectAction,attack as attackAction,dealDamage as dealDamageAction,editCooldowns as editCooldownsAction,editStatusEffect as editStatusEffectAction,editTurnTime as editTurnTimeAction,gainHealth as gainHealthAction,idle as idleAction,removeStatusEffect as removeStatusEffectAction,takeDamage as takeDamageAction }
