import addStatusEffect from './common/addStatusEffect.js'
if(!(addStatusEffect instanceof Function)) addStatusEffect.id = 'addStatusEffect'
if(!(addStatusEffect instanceof Function)) addStatusEffect.group = 'common'
import attack from './common/attack.js'
if(!(attack instanceof Function)) attack.id = 'attack'
if(!(attack instanceof Function)) attack.group = 'common'
import dealDamage from './common/dealDamage.js'
if(!(dealDamage instanceof Function)) dealDamage.id = 'dealDamage'
if(!(dealDamage instanceof Function)) dealDamage.group = 'common'
import editCooldowns from './common/editCooldowns.js'
if(!(editCooldowns instanceof Function)) editCooldowns.id = 'editCooldowns'
if(!(editCooldowns instanceof Function)) editCooldowns.group = 'common'
import editStatusEffect from './common/editStatusEffect.js'
if(!(editStatusEffect instanceof Function)) editStatusEffect.id = 'editStatusEffect'
if(!(editStatusEffect instanceof Function)) editStatusEffect.group = 'common'
import editTurnTime from './common/editTurnTime.js'
if(!(editTurnTime instanceof Function)) editTurnTime.id = 'editTurnTime'
if(!(editTurnTime instanceof Function)) editTurnTime.group = 'common'
import gainHealth from './common/gainHealth.js'
if(!(gainHealth instanceof Function)) gainHealth.id = 'gainHealth'
if(!(gainHealth instanceof Function)) gainHealth.group = 'common'
import idle from './common/idle.js'
if(!(idle instanceof Function)) idle.id = 'idle'
if(!(idle instanceof Function)) idle.group = 'common'
import removeStatusEffect from './common/removeStatusEffect.js'
if(!(removeStatusEffect instanceof Function)) removeStatusEffect.id = 'removeStatusEffect'
if(!(removeStatusEffect instanceof Function)) removeStatusEffect.group = 'common'
import takeDamage from './common/takeDamage.js'
if(!(takeDamage instanceof Function)) takeDamage.id = 'takeDamage'
if(!(takeDamage instanceof Function)) takeDamage.group = 'common'
export default { addStatusEffect,attack,dealDamage,editCooldowns,editStatusEffect,editTurnTime,gainHealth,idle,removeStatusEffect,takeDamage }
